# End-to-end check for the headless CLI, driven by CTest.
#
# This is the only test that exercises the whole chain in one go — pcap file →
# capture backend → parser → SNI/DNS attribution → flow aggregation → export —
# in the process a user actually runs. The unit tests each cover one stage.
#
# Invoked as:
#   cmake -DCLI=<exe> -DPCAP=<file> -DOUT=<file> -DFORMAT=<json|csv>
#         -P check_cli_export.cmake

foreach(required CLI PCAP OUT FORMAT)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "check_cli_export.cmake: -D${required}=... is required")
    endif()
endforeach()

if(NOT EXISTS "${PCAP}")
    message(FATAL_ERROR "sample capture is missing: ${PCAP}\n"
                        "It is generated by the NetProbeSamplePcap target during a normal build.")
endif()

# Start from a clean slate so a stale file from an earlier run cannot make a
# failing export look like a passing one.
file(REMOVE "${OUT}")

execute_process(
    COMMAND "${CLI}" --read "${PCAP}" --output "${OUT}" --format "${FORMAT}"
    RESULT_VARIABLE exit_status
    OUTPUT_VARIABLE standard_output
    ERROR_VARIABLE standard_error
)

if(NOT exit_status EQUAL 0)
    message(FATAL_ERROR "netprobe-cli exited with ${exit_status}\n"
                        "stdout:\n${standard_output}\nstderr:\n${standard_error}")
endif()

if(NOT EXISTS "${OUT}")
    message(FATAL_ERROR "netprobe-cli reported success but wrote no file to ${OUT}")
endif()

file(READ "${OUT}" exported)
if(exported STREQUAL "")
    message(FATAL_ERROR "netprobe-cli wrote an empty file to ${OUT}")
endif()

if(FORMAT STREQUAL "json")
    # Structural keys, plus a value that can only appear if hostname
    # attribution survived the whole pipeline rather than just the bytes.
    set(expected "\"flows\"" "\"src_ip\"" "\"protocol\": \"TCP\"" "\"protocol\": \"UDP\"" "cdn.netprobe.test")
else()
    set(expected "host,src_ip,src_port" "cdn.netprobe.test" "TCP" "UDP")
endif()

foreach(needle IN LISTS expected)
    string(FIND "${exported}" "${needle}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "exported ${FORMAT} is missing '${needle}'\n"
                            "----- contents -----\n${exported}")
    endif()
endforeach()

message(STATUS "netprobe-cli exported ${FORMAT} with the expected flows")
